AWSTemplateFormatVersion: "2010-09-09"


Description: Stack template for creating common resources for a project.


Parameters:
  ProjectNameParam:
    Type: String
    Description: Project name tag
    Default: "glue-stepfunction"

  EnvParam:
    Type: String
    Description: Environment tag
    Default: "dev"
    AllowedValues:
      - "prod"
      - "dev"
      - "qa"
      - "test"

  ResourceRandom:
    Type: String
    Description: Characters appended to resource name to differentiate stack resources


Resources:
  EltRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${ProjectNameParam}-ec2-role-${ResourceRandom}-${EnvParam}"
      Path: "/developer/"
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/DeveloperPermissionBoundaryPolicy"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: JenkinsPolicies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  DynamoTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "s3_path"
          AttributeType: "S"
        - AttributeName: "date_created"
          AttributeType: "S"
        - AttributeName: "execution_retry_count"
          AttributeType: "N"
        - AttributeName: "execution_status"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification:
        Enabled: "true"
      DeletionProtectionEnabled: "false"
      GlobalSecondaryIndexes:
        - ContributorInsightsSpecification:
            Enabled: "true"
          IndexName: "JobExecutionStatus"
          KeySchema:
            - AttributeName: "execution_status"
              KeyType: "HASH"
            - AttributeName: "s3_path"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "date_created"
              - "execution_retry_count"
            ProjectionType: "INCLUDE"
        - ContributorInsightsSpecification:
            Enabled: "true"
          IndexName: "JobExecutionCount"
          KeySchema:
            - AttributeName: "execution_count"
              KeyType: "HASH"
            - AttributeName: "s3_path"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "date_created"
              - "execution_status"
            ProjectionType: "INCLUDE"
      KeySchema:
        - AttributeName: "s3_path"
          KeyType: "HASH"
        - AttributeName: "date_created"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - IndexName: "RetryCount"
          KeySchema:
            - AttributeName: "s3_path"
              KeyType: "HASH"
            - AttributeName: "execution_retry_count"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "date_created"
              - "execution_status"
            ProjectionType: "INCLUDE"
        - IndexName: "ExecStatus"
          KeySchema:
            - AttributeName: "s3_path"
              KeyType: "HASH"
            - AttributeName: "execution_status"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "date_created"
              - "execution_retry_count"
            ProjectionType: "INCLUDE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: "true"
      SSESpecification:
        KMSMasterKeyId: !Ref EncryptionKey
        SSEEnabled: "true"
        SSEType: "KMS"
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      TableClass: "STANDARD"
      TableName: !Sub "${ProjectNameParam}-dynamodb-${ResourceRandom}-${EnvParam}"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-dynamodb-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  EncryptionKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: !Sub "Symmetric encryption key for server ${ProjectNameParam}"
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: !Sub "${ProjectNameParam}-key-${ResourceRandom}-${EnvParam}"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !GetAtt [EltRole, Arn]
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
              - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: '*'
      KeySpec: "SYMMETRIC_DEFAULT"
      KeyUsage: "ENCRYPT_DECRYPT"
      MultiRegion: false
      PendingWindowInDays: 7
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-crypt-sym-key-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  SnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      ContentBasedDeduplication: "true"
      DisplayName: !Sub "${ProjectNameParam}-sns-topic-${ResourceRandom}-${EnvParam} Failure Notification"
      FifoTopic: "false"
      KmsMasterKeyId: !Ref EncryptionKey
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-crypt-sym-key-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam
      TopicName: !Sub "${ProjectNameParam}-sns-topic-${ResourceRandom}-${EnvParam}"


Outputs:
  EltRole:
    Description: "Role ARN"
    Value: !Ref EltRole
    Export:
      Name: !Sub "${AWS::StackName}-elt-role"
  DynamoTable:
    Description: "Job config Dynamo table ARN"
    Value: !Ref DynamoTable
    Export:
      Name: !Sub "${AWS::StackName}-dynamo-table"
  CryptKey:
    Description: "KMS key ARN"
    Value: !Ref EncryptionKey
    Export:
      Name: !Sub "${AWS::StackName}-crypt-key"
  SnsTopic:
    Description: "KMS key ARN"
    Value: !Ref SnsTopic
    Export:
      Name: !Sub "${AWS::StackName}-sns-topic"
