AWSTemplateFormatVersion: "2010-09-09"


Description: Stack template for creating common resources for a project.


Parameters:
  ProjectNameParam:
    Type: String
    Description: Project name tag
    Default: "glue-stepfunction"

  EnvParam:
    Type: String
    Description: Environment tag
    Default: "dev"
    AllowedValues:
      - "prod"
      - "dev"
      - "qa"
      - "test"

  ResourceRandom:
    Type: String
    Description: Characters appended to resource name to differentiate stack resources


# TODO: Prevent escalation of privileges by restricting policy on permission boundary.
Resources:
  EltRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${ProjectNameParam}-ec2-role-${ResourceRandom}-${EnvParam}"
      Path: "/developer/"
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/DeveloperPermissionBoundaryPolicy"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
                - glue.amazonaws.com
                - dynamodb.amazonaws.com
                - kms.amazonaws.com
                - lambda.amazonaws.com
                - s3.amazonaws.com
                - redshift.amazonaws.com
                - sns.amazonaws.com
                - events.amazonaws.com
                - cloudtrail.amazonaws.com
                - logs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: JenkinsPolicies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  DynamoTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "s3_path"
          AttributeType: "S"
        - AttributeName: "date_created"
          AttributeType: "S"
        - AttributeName: "execution_retry_count"
          AttributeType: "N"
        - AttributeName: "execution_status"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification:
        Enabled: true
      DeletionProtectionEnabled: false
      GlobalSecondaryIndexes:
        - ContributorInsightsSpecification:
            Enabled: true
          IndexName: "JobExecutionStatus"
          KeySchema:
            - AttributeName: "execution_status"
              KeyType: "HASH"
            - AttributeName: "s3_path"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "date_created"
              - "execution_retry_count"
            ProjectionType: "INCLUDE"
        - ContributorInsightsSpecification:
            Enabled: true
          IndexName: "JobExecutionCount"
          KeySchema:
            - AttributeName: "execution_retry_count"
              KeyType: "HASH"
            - AttributeName: "s3_path"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "date_created"
              - "execution_status"
            ProjectionType: "INCLUDE"
      KeySchema:
        - AttributeName: "s3_path"
          KeyType: "HASH"
        - AttributeName: "date_created"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - IndexName: "RetryCount"
          KeySchema:
            - AttributeName: "s3_path"
              KeyType: "HASH"
            - AttributeName: "execution_retry_count"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "date_created"
              - "execution_status"
            ProjectionType: "INCLUDE"
        - IndexName: "ExecStatus"
          KeySchema:
            - AttributeName: "s3_path"
              KeyType: "HASH"
            - AttributeName: "execution_status"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "date_created"
              - "execution_retry_count"
            ProjectionType: "INCLUDE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        KMSMasterKeyId: !Ref EncryptionKey
        SSEEnabled: true
        SSEType: "KMS"
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      TableClass: "STANDARD"
      TableName: !Sub "${ProjectNameParam}-dynamodb-${ResourceRandom}-${EnvParam}"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-dynamodb-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  EncryptionKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: !Sub "Symmetric encryption key for server ${ProjectNameParam}"
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: !Sub "${ProjectNameParam}-key-${ResourceRandom}-${EnvParam}"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !GetAtt [EltRole, Arn]
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
              - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: '*'
      KeySpec: "SYMMETRIC_DEFAULT"
      KeyUsage: "ENCRYPT_DECRYPT"
      MultiRegion: false
      PendingWindowInDays: 7
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-crypt-sym-key-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  SnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: !Sub "${ProjectNameParam}-sns-topic-${ResourceRandom}-${EnvParam} Failure Notification"
      FifoTopic: false
      KmsMasterKeyId: !Ref EncryptionKey
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-crypt-sym-key-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam
      TopicName: !Sub "${ProjectNameParam}-sns-topic-${ResourceRandom}-${EnvParam}"

  PrjS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref EncryptionKey
              SSEAlgorithm: "aws:kms"
      BucketName: !Sub "${ProjectNameParam}-job-${ResourceRandom}-${EnvParam}-${AWS::Region}"
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 30
            Id: "DeleteOldAbortedMultipartUpload"
            Status: "Enabled"
          - ExpirationInDays: 30
            Id: "DeleteOldObjects"
            Status: "Enabled"
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      ObjectLockEnabled: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-job-${ResourceRandom}-${EnvParam}-${AWS::Region}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

#
#  PrjBucketPolicy:
#    Type: "AWS::S3::BucketPolicy"
#    Properties:
#      Bucket: !Ref PrjS3Bucket
#      PolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Action: "s3:GetBucketAcl"
#            Effect: Allow
#            Resource: !Sub "arn:aws:s3:::${PrjS3Bucket}"
#            Principal:
#              Service: "cloudtrail.amazonaws.com"
#            Condition:
#              StringLike:
#                "aws:SourceArn": !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/*"
#          - Action: "s3:PutObject"
#            Effect: Allow
#            Resource: !Sub "arn:aws:s3:::${PrjS3Bucket}/trail/AWSLogs/${AWS::AccountId}/*"
#            Principal:
#              Service: "cloudtrail.amazonaws.com"
#            Condition:
#              StringEquals:
#                "s3:x-amz-acl": "bucket-owner-full-control"
#              StringLike:
#                "aws:SourceArn": !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/*"
##          - Action: "s3:PutObject"
##            Effect: Allow
##            Resource: !Sub "arn:aws:s3:::${PrjS3Bucket}/${JobName}/AWSLogs/${AWS::AccountId}/*"
##            Principal:
##              Service: "cloudtrail.amazonaws.com"
##            Condition:
##              StringEquals:
##                "s3:x-amz-acl": "bucket-owner-full-control"
##              StringLike:
##                "aws:SourceArn": !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/*"


  DataS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref EncryptionKey
              SSEAlgorithm: "aws:kms"
      BucketName: !Sub "${ProjectNameParam}-data-${ResourceRandom}-${EnvParam}-${AWS::Region}"
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 30
            Id: "DeleteOldAbortedMultipartUpload"
            Status: "Enabled"
          - ExpirationInDays: 30
            Id: "DeleteOldObjects"
            Status: "Enabled"
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      ObjectLockEnabled: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-data-${ResourceRandom}-${EnvParam}-${AWS::Region}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  EventBus:
    Type: "AWS::Events::EventBus"
    Properties:
      Name: !Sub "${ProjectNameParam}-s3-write-eventbus-${ResourceRandom}-${EnvParam}"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-s3-write-eventbus-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam


Outputs:
  EltRoleName:
    Description: "Role Name"
    Value: !Ref EltRole
    Export:
      Name: !Sub "${AWS::StackName}-elt-role-name"

  EltRoleArn:
    Description: "Role ARN"
    Value: !GetAtt EltRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-elt-role-arn"

  DynamoTable:
    Description: "Job config Dynamo table ARN"
    Value: !Ref DynamoTable
    Export:
      Name: !Sub "${AWS::StackName}-dynamo-table"

  CryptKeyId:
    Description: "KMS key Id"
    Value: !Ref EncryptionKey
    Export:
      Name: !Sub "${AWS::StackName}-crypt-key-id"

  CryptKeyArn:
    Description: "KMS key ARN"
    Value: !GetAtt EncryptionKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-crypt-key-arn"

  SnsTopic:
    Description: "Sns Topic ARN"
    Value: !Ref SnsTopic
    Export:
      Name: !Sub "${AWS::StackName}-sns-topic"

  EventBus:
    Description: "Event bus name"
    Value: !Ref EventBus
    Export:
      Name: !Sub "${AWS::StackName}-event-bus"

  DataS3Bucket:
    Description: "Data bucket name"
    Value: !Ref DataS3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-data-bucket"

  PrjS3Bucket:
    Description: "Job bucket name"
    Value: !Ref PrjS3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-job-bucket"
